### ISSUE TITLE
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json

### ISSUE THREAD

**Issue by teuteuguy** [neo-ai/neo-ai-dlr#190]
Trying to compile neo-ai-dlr as per documentation.

When trying to run the python load_and_run_tvm_model.py it fails on:

Preparing model artifacts for resnet18_v1 ...
Preparing model artifacts for mobilenet_v1_0.75_224_quant ...
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 10
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 9
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 8
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 7
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 6
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 5
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 4
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 3
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 2
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 1
Traceback (most recent call last):
File "/home/tim/Downloads/neo-ai-dlr/tests/python/integration/test_utils.py", line 45, in get_models
urlretrieve(s3_path, local_path)
File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
with contextlib.closing(urlopen(url, data)) as fp:
File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.7/urllib/request.py", line 531, in open
response = meth(req, response)
File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.7/urllib/request.py", line 569, in error
return self._call_chain(*args)
File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
result = func(*args)
File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by apivovarov** [comment]
`mobilenet_v1_0.75_224_quant/ec2_a1.json` was uploaded. Can you try again?

**Comment by teuteuguy** [comment]
Hi, now the asset is there. Thanks. However the test file load_and_run_tvm_model.py still fails.

Preparing model artifacts for resnet18_v1 ...
Preparing model artifacts for mobilenet_v1_0.75_224_quant ...
Preparing model artifacts for 4in2out ...
Preparing model artifacts for assign_op ...
[15:50:38] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:71: No metadata found
[15:50:40] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:231: No metadata file was found!
Testing inference on resnet18...
[15:50:40] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:71: No metadata found
[15:50:40] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:231: No metadata file was found!
Testing inference on mobilenet_v1_0.75_224_quant...
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:71: No metadata found
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:231: No metadata file was found!
Testing inference on mobilenet_v1_0.75_224_quant with float32 input...
2020-06-02 15:50:41,695 ERROR error in running inference DLRModelImpl input data with name input should have dtype uint8 but float32 is provided
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 89, in run
    return self._impl.run(input_values)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 436, in run
    self._set_input(key, value)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 310, in _set_input
    format(name, input_dtype, data.dtype.name))
ValueError: input data with name input should have dtype uint8 but float32 is provided
2020-06-02 15:50:41,695 ERROR error in running inference DLRModelImpl input data with name input should have dtype uint8 but float32 is provided
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 89, in run
    return self._impl.run(input_values)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 436, in run
    self._set_input(key, value)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 310, in _set_input
    format(name, input_dtype, data.dtype.name))
ValueError: input data with name input should have dtype uint8 but float32 is provided
2020-06-02 15:50:41,695 ERROR error in running inference DLRModelImpl input data with name input should have dtype uint8 but float32 is provided
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 89, in run
    return self._impl.run(input_values)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 436, in run
    self._set_input(key, value)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 310, in _set_input
    format(name, input_dtype, data.dtype.name))
ValueError: input data with name input should have dtype uint8 but float32 is provided
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:71: No metadata found
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:231: No metadata file was found!
Testing multi_input/multi_output support...
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:71: No metadata found
[15:50:41] /home/tim/Downloads/neo-ai-dlr/src/dlr_tvm.cc:231: No metadata file was found!
Testing _assign() operator...
2020-06-02 15:50:41,708 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1
2020-06-02 15:50:41,708 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1
2020-06-02 15:50:41,708 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1
2020-06-02 15:50:41,708 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1
2020-06-02 15:50:41,708 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1
Traceback (most recent call last):
  File "load_and_run_tvm_model.py", line 114, in <module>
    test_assign_op()
  File "load_and_run_tvm_model.py", line 98, in test_assign_op
    input1_next = model.get_input('w2', shape=(5, 3, 18, 18))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 106, in get_input
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 103, in get_input
    return self._impl.get_input(name, shape)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 464, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 289, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/usr/local/lib/python3.7/dist-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 250, in get_input_dtype
    raise Exception(f"Index cannot be greater than {self.num_inputs - 1}")
Exception: Index cannot be greater than 1

**Comment by nabulsi** [comment]
Hi,
I am getting the same error message. I have built from Neo on Jetson Nano. As per the doc page, I want to test the installation by running 
```
cd tests/python/integration/
python3 load_and_run_tvm_model.py
```

However, it fails with:
```
ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
2020-07-24 09:50:57,195 ERROR error in getting inputs DLRModelImpl Index cannot be greater than 1
Traceback (most recent call last):
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
Traceback (most recent call last):
  File "load_and_run_tvm_model.py", line 114, in <module>
    test_assign_op()
  File "load_and_run_tvm_model.py", line 98, in test_assign_op
    input1_next = model.get_input('w2', shape=(5, 3, 18, 18))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 162, in get_input
    raise ex
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/api.py", line 159, in get_input
    return self._impl.get_input(name, shape)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 492, in get_input
    input_dtype = self._get_input_or_weight_dtype_by_name(name)
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 317, in _get_input_or_weight_dtype_by_name
    return self.get_input_dtype(self._get_input_index(name))
  File "/home/jetson/.local/lib/python3.7/site-packages/dlr-1.2.0-py3.7.egg/dlr/dlr_model.py", line 278, in get_input_dtype
    raise Exception("Index cannot be greater than {}".format(self.num_inputs - 1))
Exception: Index cannot be greater than 1
```

Can you please look into it?

Thanks

**Comment by ashsyal** [comment]
Hi,
I get the same error as above? Any resolution?
reparing model artifacts for xgboost-mnist-1.10.0 ...
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 10
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 9
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 8
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 7
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 6
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 5
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 4
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 3
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 2
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/xgboost-mnist-1.10.0/ec2_a1.so on try 1
