### ISSUE TITLE
Jetson Xavier Inference Crashes on TRT8

### ISSUE THREAD

**Issue by mycpuorg** [neo-ai/neo-ai-dlr#411]
DLR Build Machine (and target machine both) is NVidia Jetson Xavier AGX.
Ubuntu 18.04 JetPack4.6
Software Info:

```
xavier:~$ jetson_release 
 - NVIDIA Jetson AGX Xavier [16GB]
   * Jetpack 4.6 [L4T 32.6.1]
   * NV Power Mode: MODE_15W_DESKTOP - Type: 7
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.300
   * cuDNN: 8.2.1.32
   * TensorRT: 8.0.1.6
   * Visionworks: 1.6.0.501
   * OpenCV: 4.1.1 compiled CUDA: NO
   * VPI: ii libnvvpi1 1.1.15 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70
```
Follow directions to build DLR on Jetson [here](https://neo-ai-dlr.readthedocs.io/en/latest/install.html#building-for-nvidia-gpu-on-jetson-devices)

```
Caught SIGSEGV
#0  0x0000007fac68ed5c in __waitpid (pid=<optimized out>, stat_loc=0x7fc9af1744, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000007fac6ca2e0 in g_on_error_stack_trace ()
#2  0x0000005558e75c3c in  ()
#3  0x000000555d330930 in  ()
Spinning.  Please run 'gdb gst-launch-1.0 16016' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump 
```

**Comment by mycpuorg** [comment]
Recommendation provided in the Issue #409 builds DLR successfully for TRT8 however, using a model compiled with Neo for a previous revision of TRT (JetPack4.4) crashes with a SEGFAULT during Inference.
