### ISSUE TITLE
Executing load_and_run_tvm_model.py failed

### ISSUE THREAD

**Issue by AiprNick** [neo-ai/neo-ai-dlr#74]
Hi all,
I installed the DLR with whl[2] from doc.[1]
Next, I did git clone and python3 load_and_run_tvm_model.py to valid the DLR.

However, I got the error message like this:

```
nick@AWS-JN:~/AI/neo-ai-dlr/tests/python/integration$ python3 load_and_run_tvm_model.py 
Preparing model artifacts for resnet18_v1 ...
Preparing model artifacts for 4in2out ...
Preparing model artifacts for assign_op ...
Traceback (most recent call last):
  File "/home/nick/AI/neo-ai-dlr/tests/python/integration/test_utils.py", line 43, in get_models
    urlretrieve(s3_path, local_path) 
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load_and_run_tvm_model.py", line 67, in <module>
    get_models(model_name, arch, kind='tvm')
  File "/home/nick/AI/neo-ai-dlr/tests/python/integration/test_utils.py", line 45, in get_models
    raise ValueError('Downloading of model artifacts from %s failed' % s3_path)
ValueError: Downloading of model artifacts from https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/assign_op/ec2_a1.json failed
```

Do you meet the problem before?

Here is my test bed information:
```
Hardware : Nvidia Jetson Nano
OS : Ubuntu 18.04.2 LTS
Kernel : 4.9.140-tegra
python3, pip3 : python 3.6.8
dlr : version 1.0
```

[1] : https://neo-ai-dlr.readthedocs.io/en/latest/install.html
[2] : https://s3-us-west-2.amazonaws.com/neo-ai-dlr-release/v1.0/jetsonnano-aarch64-cu10-ubuntu18_04-glibc2_27-libstdcpp3_4/dlr-1.0-py2.py3-none-any.whl

**Comment by hcho3** [comment]
@AiprNick We uploaded the test artifacts for ARM target to the S3 bucket (shown in the error message). Can you try running the script again?

**Comment by AiprNick** [comment]
@hcho3 Thanks!  However, I still met these problems when executing load_and_run_tvm_model.py  ..

There are three cases in this test script:

**1. test_resnet()**
Status: **PASS**
Message:
`Testing inference on resnet18...`

**2. test_multi_input_multi_output()**
Status: **FAIL**
Message:
```
Traceback (most recent call last):
  File "load_and_run_tvm_model.py", line 69, in <module>
    test_multi_input_multi_output()
  File "load_and_run_tvm_model.py", line 30, in test_multi_input_multi_output
    assert model._impl._get_output_size_dim(0) == (2, 1)
AttributeError: 'DLRModel' object has no attribute '_impl'
``` 
**3. test_assign_op()**
Status: **FAIL**
Message:
```
Traceback (most recent call last):
  File "load_and_run_tvm_model.py", line 70, in <module>
    test_assign_op()
  File "load_and_run_tvm_model.py", line 56, in test_assign_op
    input1_next = model.get_input('w2', shape=(5, 3, 18, 18))
AttributeError: 'DLRModel' object has no attribute 'get_input'
```

Do I lack of some dependency settings?

**Comment by hcho3** [comment]
The 1.0 release came out on March 21, and the tests refer to some features that have been introduced after the 1.0 release. Would you be able to compile DLR from the latest source? In the meanwhile, we will start working on a new release to include all latest features.

**Comment by AiprNick** [comment]
Okay. I'll try to build the latest source. Thanks!

**Comment by teuteuguy** [comment]
Trying to compile neo-ai-dlr as per documentation.

When trying to run the python load_and_run_tvm_model.py it fails on:

Preparing model artifacts for resnet18_v1 ...
Preparing model artifacts for mobilenet_v1_0.75_224_quant ...
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 10
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 9
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 8
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 7
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 6
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 5
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 4
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 3
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 2
Error downloading https://s3-us-west-2.amazonaws.com/neo-ai-dlr-test-artifacts/mobilenet_v1_0.75_224_quant/ec2_a1.json on try 1
Traceback (most recent call last):
  File "/home/tim/Downloads/neo-ai-dlr/tests/python/integration/test_utils.py", line 45, in get_models
    urlretrieve(s3_path, local_path)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
